spring.application.name=KafkaWkShp001
# Kafka (your Linux box running Docker)
spring.kafka.bootstrap-servers=192.168.1.5:9092
spring.kafka.consumer.enable-auto-commit=true
spring.kafka.consumer.auto-commit-interval=5000
spring.kafka.consumer.properties.max.poll.interval.ms=300000

# Elasticsearch
spring.elasticsearch.uris=http://192.168.1.5:9200

auto.create.topics.enable=true
#app.kafka.topic=test

#app.kafka.topic=network-events
app.kafka.topic=firewall.logs.raw

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

#key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
#value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
#
#key.serializer=org.apache.kafka.common.serialization.StringSerializer
#value.serializer=org.apache.kafka.common.serialization.StringSerializer

server.port=8080

#postgres
spring.datasource.url=jdbc:postgresql://192.168.1.5:5433/workshopdb
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.root=INFO
logging.level.com.dcfaight.kafkawkshp001=INFO
